Remove chain:block from documentation
iron-fish/website pull request #147
Opened 2022-02-10 02:45 UTC by AmberKiso

## Summary
Fix #976 by removing command from CLI documentation.

## Testing Plan
Ran the local website, chain:block removed

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
[X] No
```

2022-02-12 08:16 UTC, dguenther requested changes
This got moved to `blocks:show` in this PR: https://github.com/iron-fish/ironfish/pull/871 If you wouldn't mind updating the docs, that'd be great!

2022-02-12 23:24 UTC, AmberKiso commented
You got it!

(Checked it on localhost build.)

2022-02-12 23:32 UTC, dguenther approved these changes
Looks great, thank you!

2022-02-12 23:33 UTC, merged

2022-02-13 00:22 UTC, AmberKiso commented
You're welcome!